[Gabriel Costa] Entity "incidente", DbContext, DbSet, db connection and first migration
programador-tv/boca-suja pull request #7
Opened 2023-07-04 16:15 UTC by gmessiasc

- Entity "Incidente" with constructor.
- "Incident" instantiate test.
- Adding "HEALTH.Check()" static method.
- "BocaSujaDbContext" was built.
- "IncidenteDbMapping" was built.
- First migration using EF Core Tools.

2023-07-05 22:05 UTC, eduardoworrel requested changes

2023-07-05 22:05 UTC, eduardoworrel commented on Apps/Core.BocaSuja/Domain/Entities/Incidencia.cs
> +    public DateTimeOffset DataHoraCriacao { get; private set; }
🥇

2023-07-05 22:05 UTC, eduardoworrel commented on Apps/Core.BocaSuja/Domain/Entities/Incidencia.cs
> +    public Guid Id { get; private set; }
**Comentário:** seria interessante termos um baseModel em que todas as entidades herdariam. de qualquer forma enquanto esta for nossa única entidade acredito que não tem problema, o que você acha a respeito?

2023-07-05 22:05 UTC, eduardoworrel commented on Apps/Core.BocaSuja/Domain/Entities/Incidencia.cs
> +    public Guid Id { get; private set; }
**Solicitação de mudança:** creio eu que seja necessário indicar que este campo é uma chave primária, seria com a notation [Key] ou no DbMap `Apps/Web.Api.BocaSuja/Context/DbMapping/IncidenciaDbMapping.cs`

posso estar desatualizado, se não fizer sentido só dizer ;)

2023-07-05 22:05 UTC, eduardoworrel commented on Apps/Web.Api.BocaSuja/Program.cs
> +using (var scope = app.Services.CreateScope())
**Sugestão:** para estendermos a cobertura de código para este trecho podemos criar um método estático em um arquivo (algo como `dbHealthCheck.cs`) que checa a criação do banco de dados;

ele pode receber o app.Service e abrir o scope no contexto próprio.

Faz sentido pra você?

2023-07-05 22:08 UTC, gmessiasc commented on Apps/Core.BocaSuja/Domain/Entities/Incidencia.cs
> +    public Guid Id { get; private set; }
eu concordo, inclusive acho que seria bacana esse base model ter outros atributos como: o momento em que foi atualizado e um a flag de deleção para soft delete quando necessário

2023-07-05 22:13 UTC, gmessiasc commented on Apps/Core.BocaSuja/Domain/Entities/Incidencia.cs
> +    public Guid Id { get; private set; }
já está sendo indicado como chave primária no Apps/Web.Api.BocaSuja/Context/DbMapping/IncidenciaDbMapping.cs
na linha 12

optei por usar o fluent api por tudo porque acho que dá para ter mais controle sobre algumas coisas da db, mas podemos mudar a estratégia sem problema

2023-07-06 14:08 UTC, eduardoworrel approved these changes

2023-07-06 14:10 UTC, merged